// pop-demo-gen：注入 Tailwind Play CDN 的配置（镜像 apps/web/tailwind.config.ts 的 theme.extend）。
// 在 demo 里于加载 ./tailwind.js 之后、<body> 之前以 <script> 内联赋值 tailwind.config。
// 颜色/圆角/字号引用 <style> 里内联的 CSS 变量，故必须与 tokens.css 一起使用。
tailwind.config = {
  theme: {
    extend: {
      borderRadius: {
        card: 'var(--radius-card)',
        'card-inner': 'var(--radius-card-inner)',
        cta: 'var(--radius-cta)',
        pill: 'var(--radius-pill)',
        search: 'var(--radius-search)',
        tag: 'var(--radius-tag)',
      },
      colors: {
        'accent-blue': 'var(--color-accent-blue)',
        'accent-danger': 'var(--color-accent-danger)',
        'accent-green': 'var(--color-accent-green)',
        'accent-pink': 'var(--color-accent-pink)',
        'accent-yellow': 'var(--color-accent-yellow)',
        'brand-dark': 'var(--color-brand-dark)',
        'brand-darker': 'var(--color-brand-darker)',
        'brand-darkest': 'var(--color-brand-darkest)',
        'brand-light': 'var(--color-brand-light)',
        'brand-lighter': 'var(--color-brand-lighter)',
        'brand-lightest': 'var(--color-brand-lightest)',
        'brand-link': 'var(--color-brand-link)',
        'brand-normal': 'var(--color-brand-normal)',
        'btn-danger': 'var(--color-btn-danger)',
        'btn-primary-bg': 'var(--color-btn-primary-bg)',
        'btn-primary-text': 'var(--color-btn-primary-text)',
        'btn-secondary-border': 'var(--color-btn-secondary-border)',
        'btn-secondary-text': 'var(--color-btn-secondary-text)',
        'neutral-1': 'var(--color-neutral-1)',
        'neutral-2': 'var(--color-neutral-2)',
        'neutral-3': 'var(--color-neutral-3)',
        'neutral-4': 'var(--color-neutral-4)',
        'neutral-5': 'var(--color-neutral-5)',
        'neutral-6': 'var(--color-neutral-6)',
        'neutral-7': 'var(--color-neutral-7)',
        placeholder: 'var(--color-text-placeholder)',
        primary: 'var(--color-text-primary)',
        quaternary: 'var(--color-text-quaternary)',
        secondary: 'var(--color-text-secondary)',
        tertiary: 'var(--color-text-tertiary)',
        title: 'var(--color-title)',
      },
      fontSize: {
        body: 'var(--text-body)',
        'body-lg': 'var(--text-body-lg)',
        'body-strong': 'var(--text-body-strong)',
        caption: 'var(--text-caption)',
        display: 'var(--text-display)',
        heading: 'var(--text-title)',
        'heading-lg': 'var(--text-title-lg)',
        label: 'var(--text-label)',
        subtitle: 'var(--text-subtitle)',
      },
      maxWidth: { 92: '23rem', 360: '90rem' },
      spacing: { 15: '3.75rem', 18: '4.5rem' },
    },
  },
};
